### PR TITLE
4.x - Solr search exclusions and Fedora Generic Search multi-threading

### PR DESCRIPTION
**Pull request by CanOfBees**
## What does this pull request do?

This PR provides the following updates:
1. Solr search exclusions (e.g. undescribed collection and islandora namespace objects)
2. Configuration files for multi-threading the fedoragsearch webapp
## What's new?

Lots. There are updates to the README, new directories for the various configuration files, modifications to those configuration files, as well as minor updates to the islandora_transforms.
## How should this be tested?

The truth is that some of the changes are already in place on dev and production; this is the case for many of the islandora_transforms tweaks and the fedoragsearch performance updates. 

Testing /reviewing the changes made to solr-conf/solrconfig.xml is possible. These changes have not been deployed to production.

**note:** this assumes that you are using a minimal vm and do not have islandora_collection_search installed.
- start your vm
- visit ~~`http://localhost:8080/solr/collection1/select?q=%3a&lf=PID&wt=xml&indent=true`~~ `http://localhost:8080/solr/collection1/select?q=*%3A*&fl=PID&wt=xml&indent=true`
- this Solr query returns the first 10 items in the index - it should look something like this:

``` xml
<response>

<lst name="responseHeader">
  <int name="status">0</int>
  <int name="QTime">0</int>
  <lst name="params">
    <str name="q">*:*</str>
    <str name="indent">true</str>
    <str name="fl">PID</str>
    <str name="wt">xml</str>
  </lst>
</lst>
<result name="response" numFound="46" start="0">
  <doc>
    <str name="PID">islandora:bookCollection</str></doc>
  <doc>
    <str name="PID">islandora:compound_collection</str></doc>
  <doc>
    <str name="PID">islandora:sp_disk_image_collection</str></doc>
  <doc>
    <str name="PID">islandora:sp_pdf_collection</str></doc>
  <doc>
    <str name="PID">islandora:video_collection</str></doc>
  <doc>
    <str name="PID">islandora:sp_web_archive_collection</str></doc>
...[snip]...
```

To **exclude** the first two results, `islandora:bookCollection` and `islandora:compound_collection`
- use your favorite text editor to modify `/usr/local/solr/collection1/conf/solrconfig.xml`; e.g.
  - `$ sudo vim /usr/local/solr/collection1/conf/solrconfig.xml`
- at approximately line 800, add the following and save the file

``` xml
<lst name="appends">
  <str name="fq">-PID:islandora\:bookCollection -PID:islandora\:compound_collection</str>
</lst>
```
- restart Tomcat; e.g. `$ sudo service tomcat7 restart`
- after Tomcat has restarted, revisit the previous link ~~`http://localhost:8080/solr/collection1/select?q=%3a&lf=PID&wt=xml&indent=true`~~ `http://localhost:8080/solr/collection1/select?q=*%3A*&fl=PID&wt=xml&indent=true`. The PIDs you chose to exclude should not be in the query results.
## Interested Parties

@pc37utn @DonRichards 

**edit:** removed a Solr query that got copied incorrectly.
**edit:** fixed garbled Solr query URLs. oops. :/
**edit:** added note re `sudo` and modifying solrconfig.xml

### CODE REVIEW

**Comment by pc37utn** [comment]
Okay, I did the first solr query and this is what I am seeing:
`<response>
<lst name="responseHeader">
<int name="status">400</int>
<int name="QTime">7</int>
<lst name="params">
<str name="q">:</str>
<str name="indent">true</str>
<str name="lf">PID</str>
<str name="wt">xml</str>
</lst>
</lst>
<lst name="error">
<str name="msg">
org.apache.solr.search.SyntaxError: Cannot parse ':': Encountered " ":" ": "" at line 1, column 0. Was expecting one of: <NOT> ... "+" ... "-" ... <BAREOPER> ... "(" ... "*" ... <QUOTED> ... <TERM> ... <PREFIXTERM> ... <WILDTERM> ... <REGEXPTERM> ... "[" ... "{" ... <LPARAMS> ... <NUMBER> ... <TERM> ... "*" ...
</str>
<int name="code">400</int>
</lst>
</response>`

**Comment by CanOfBees** [comment]
@pc37utn was the VM fully started when you ran the query?

**Comment by CanOfBees** [comment]
@pc37utn the Solr URLs had a really strange problem (letters transposed and missing encoded characters) that has been fixed. Sorry about that.

**Comment by DonRichards** [comment]
For Documentation sake. Before the Pull request is tested. The instructions before this PR results in the following 

UPDATED!
before pull request_solr collection1 select q 3a lf pid wt xml indent true

**Comment by pc37utn** [comment]
After using the corrected solr query, the test worked.    One note might be that the editing of the solrconfig.xml file requires that you do a sudo -i first.

**Comment by DonRichards** [comment]
Error: `index.properties` is pointing to `/usr/local/solr/collection1/data/index`

**Comment by DonRichards** [comment]
To simplify the instructions I would use the following:
1. Start your vm
2. Browser: visit http://localhost:8080/solr/collection1/select?q=%3a&lf=PID&wt=xml&indent=true http://localhost:8080/solr/collection1/select?q=*%3A*&fl=PID&wt=xml&indent=true

#### Results: before pull request_solr collection1 select q 3a lf pid wt xml indent true

Testing Pull Request in Vagrant as a form of testing:
```terminal 
git clone https://github.com/CanOfBees/basic-solr-config.git --branch 4.x --single-branch /vagrant/basic-solr-config

git branch
* 4.x

sudo cp -r /vagrant/basic-solr-config/solr-conf/* /usr/local/solr/collection1/conf

sudo cp -r /vagrant/basic-solr-config/islandora_transforms/* /var/lib/tomcat7/webapps/fedoragsearch/WEB-INF/classes/fgsconfigFinal/index/FgsIndex/islandora_transforms/*

cd /var/lib
sudo ln -s /var/lib/ fedora

cd fedora
sudo ln -s tomcat7/ tomcat

sudo mkdir server
cd server 
sudo ln -s /usr/local/solr/collection1/conf/ config

cd /var/lib/tomcat7/webapps/fedoragsearch/WEB-INF/classes

sudo ln -s fgsconfigFinal/ config

cd /usr/local/solr/collection1/conf/
cd sudo ln -s  /usr/local/solr/collection1/conf/ solr-conf

..... Incomplete.... Still working on this
```

#### Results: 
NOT READY YET

**Pull request merged**
